// src/utils/pdfExport.js
// Lightweight, dependency-free PDF export.
// Opens a clean printable window and triggers the browser's native
// "Save as PDF" print dialog — works everywhere, no extra npm packages needed.

function escapeHtml(str = '') {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

export function exportQuestionsAsPDF({ title, subtitle, questions }) {
  if (!questions || questions.length === 0) return;

  const rows = questions
    .map(
      (q, i) => `
      <div class="q">
        <div class="q-head">
          <span class="q-num">${i + 1}.</span>
          <span class="q-tag">${escapeHtml(q.type || '')}</span>
        </div>
        <div class="q-text">${escapeHtml(q.question)}</div>
      </div>`
    )
    .join('');

  const html = `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(title)}</title>
    <style>
      * { box-sizing: border-box; }
      body {
        font-family: 'Segoe UI', Arial, sans-serif;
        color: #1a1a2e;
        padding: 40px 50px;
        max-width: 800px;
        margin: 0 auto;
      }
      .header { border-bottom: 3px solid #6366F1; padding-bottom: 16px; margin-bottom: 24px; }
      .brand { font-size: 13px; font-weight: 700; color: #6366F1; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 6px; }
      h1 { font-size: 22px; margin: 0 0 6px; }
      .subtitle { font-size: 13px; color: #555; }
      .q { padding: 14px 0; border-bottom: 1px solid #e5e5e5; }
      .q-head { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
      .q-num { font-weight: 700; color: #6366F1; font-size: 13px; }
      .q-tag {
        font-size: 10px; font-weight: 700; padding: 2px 8px; border-radius: 10px;
        background: #EEF2FF; color: #6366F1; text-transform: uppercase;
      }
      .q-text { font-size: 13.5px; line-height: 1.6; }
      .footer { margin-top: 30px; font-size: 11px; color: #999; text-align: center; }
      @media print { body { padding: 20px 30px; } }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="brand">🎯 PrepAI</div>
      <h1>${escapeHtml(title)}</h1>
      ${subtitle ? `<div class="subtitle">${escapeHtml(subtitle)}</div>` : ''}
    </div>
    ${rows}
    <div class="footer">Generated by PrepAI · ${new Date().toLocaleDateString()}</div>
  </body>
  </html>`;

  const win = window.open('', '_blank', 'width=820,height=900');
  if (!win) {
    alert('Popup blocked! Please allow popups to export PDF.');
    return;
  }
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  // give the new window a moment to render before printing
  setTimeout(() => {
    win.print();
  }, 350);
}
